"""Generate a reviewable remediation artifact from a recorded investigation.

Completes the loop:  detect → explain → map impact → route owner → open incident
→ **propose repair** → verify guard.

From a cached trace this produces, deterministically (no LLM call, no cost):
  * a **dbt schema test** (`not_null` / uniqueness) for the failing column, and
  * a **patch proposal** markdown tied to the identified root-cause lineage and
    the routed owner — explicitly marked as requiring human review/approval.

Nothing is auto-applied anywhere: the artifact is a proposal for the owner to
review, matching CASCADE's observe → propose → act rollout philosophy.

Usage:
  python scripts/propose_fix.py                 # all cached scenarios
  python scripts/propose_fix.py null_spike      # one
Artifacts land in examples/remediation/<scenario>/.
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from cascade.scenarios import SCENARIOS_BY_ID  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "demo" / "cached"
OUT = ROOT / "examples" / "remediation"


def _model_name(urn: str) -> str:
    m = re.search(r",([\w.$]+),PROD\)", urn)
    return (m.group(1).split(".")[-1] if m else "unknown").lower()


def _column(scenario: dict) -> str:
    m = re.search(r"`(\w+)`", scenario["symptom"])
    return m.group(1) if m else "affected_column"


def generate(sid: str) -> Path:
    scenario = SCENARIOS_BY_ID[sid]
    trace = json.loads((CACHE / f"{sid}.json").read_text())
    col = _column(scenario)
    affected_model = _model_name(scenario["affected_urn"])
    root_model = _model_name(scenario.get("expected_root_cause_urn", ""))
    dupe_case = "duplicat" in scenario["symptom"].lower()

    out_dir = OUT / sid
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. dbt schema test — the guard, expressed in the repo the owner already runs
    if dupe_case:
        test_yaml = f"""# PROPOSED by CASCADE — requires human review before merge
# Guard for: {scenario['name']}
version: 2
models:
  - name: {affected_model}
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [order_id, line_item_id]
          name: cascade_guard_{affected_model}_no_fanout_duplicates
    columns:
      - name: {col}
        tests: [not_null]
"""
    else:
        test_yaml = f"""# PROPOSED by CASCADE — requires human review before merge
# Guard for: {scenario['name']}
version: 2
models:
  - name: {affected_model}
    columns:
      - name: {col}
        tests:
          - not_null:
              name: cascade_guard_{affected_model}_{col}_not_null
"""
    (out_dir / f"schema_test_{affected_model}.yml").write_text(test_yaml)

    # 2. patch proposal for the owner
    owner_line = ""
    ft = trace.get("final_text") or ""
    m = re.search(r"(?:routed to|[Oo]wner(?:ed by)?:?\s*)\*{0,2}([A-Z][\w .&-]{3,40}?(?:Team|Eng\w*|Platform|Data\w*))\b", ft)
    if m and m.group(1).strip().lower() not in {"contact", "owner", "team"}:
        owner_line = f"**Proposed reviewer/owner:** {m.group(1).strip()}\n\n"
    proposal = f"""# Remediation proposal — {scenario['name']}

> Generated by CASCADE from the recorded investigation (`demo/cached/{sid}.json`).
> **Status: PROPOSAL — requires human review and approval. Nothing is auto-applied.**

{owner_line}## What broke (evidence-backed likely cause)

- Affected: `{scenario['affected_urn']}` (column `{col}`)
- Likely root cause asset (from column-level lineage): `{scenario.get('expected_root_cause_urn', 'n/a')}`
- Native incident: `{trace.get('incident_urn')}`
- Guard assertion (DataHub): `{trace.get('assertion_urn')}`

## Proposed repair steps (for the owner to verify & apply)

1. Verify the upstream load for `{root_model}`: row counts vs previous run, join-key
   integrity, and the load job's run logs.
2. Apply the dbt schema test in `schema_test_{affected_model}.yml` to the model's
   `.yml` so the failure mode is caught at build time — in addition to the DataHub
   guard assertion CASCADE already registered.
3. Backfill/refresh `{affected_model}` after the upstream fix, then resolve the
   DataHub incident.

## Why this is a proposal, not an auto-fix

Lineage identifies the fault domain; confirming the exact defect needs run logs /
row counts that live outside the catalog. CASCADE therefore contains the incident
(native incident + guard + owner alert) and hands the repair decision to a human.
"""
    (out_dir / "PROPOSAL.md").write_text(proposal)
    return out_dir


if __name__ == "__main__":
    which = sys.argv[1:] or [s for s in SCENARIOS_BY_ID
                             if (CACHE / f"{s}.json").exists()]
    for sid in which:
        print("generated:", generate(sid))
